CREATE OR REPLACE DATABASE juegos CHARACTER SET = 'utf8';
USE juegos;

CREATE TABLE JUEGOS (
	ID_JUEGO INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(150),
	ANIO INT,
	EMPRESA VARCHAR(150),

	PRIMARY KEY(ID_JUEGO)
);

ALTER TABLE JUEGOS CONVERT TO CHARACTER SET utf8;

INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Super Mario Bros 3',1988,'Nintendo');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('The Legend of Zelda',1987,'Nintendo');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Super Mario Bros',1985,'Nintendo');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Metroid ',1986,'Nintendo');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Mega Man 2',1988,'Capcom');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Castlevania III: Dráculaʼs Curse',1989,'Konami');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Kirbyʼs Adventure',1993,'Nintendo');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Super Mario Bros 2',1988,'Nintendo');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Kid Icarus',1987,'Nintendo');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Final Fantasy',1987,'Square');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Gradius',1986,'Konami');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Metal Gear',1987,'Konami');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Mike Tysonʼs Punch Out!',1987,'Nintendo');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Ninja Gaiden',1988,'Tecmo');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Contra (Probotector)',1988,'Konami');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Double Dragon',1988,'Technos Japan');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Duck Tales',1989,'Capcom');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('R.C. Pro-Am',1988,'Rare');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('MicroMachines ',1991,'Codemasters');
INSERT INTO JUEGOS (NOMBRE, ANIO, EMPRESA) VALUES ('Battletoads ',1991,'Rare');
